name: CI-damaItaliana

on: [push]

# Imposta una variabile d'ambiente, valida per tutti i job del workflow, che dice a vcpkg 
# dove salvare e da dove leggere i pacchetti già compilati 
# (la "binary cache").
# Quando vcpkg installa un pacchetto (es. glfw3), calcola un hash (l'"ABI") a partire dal codice sorgente, dal compilatore, dalle opzioni e dal triplet. Poi:
# Cerca nella binary cache un archivio con quell'hash. Se c'è, lo estrae e salta la compilazione.
# Se non c'è, compila il pacchetto e salva l'archivio nella cache per le volte successive.

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-cache

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Building Project
        run: cmake --build build --config Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      # Installiamo tutte le dipendenze di sistema richieste da vcpkg
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git automake libtool m4 pkg-config autoconf autoconf-archive \
          libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libgl1-mesa-dev
      
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          
      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=x64-linux
          
      - name: Building Project
        run: cmake --build build
