name: CI-damaItaliana

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
      - name: Configure CMake
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Building Project
        run: cmake --build build --config Release

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ale211734/italian-checker:latest
    steps:
      # 1. Installa i compilatori necessari (fondamentale)
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake git
    
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
      - name: Configure CMake
        run: >
          cmake -B build -S .
             -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Building Project
        run: cmake --build build
